language: node_js

node_js:
  - "0.10"

branches:
  only:
    - master
    - develop
    - interactive_marker_on_2d_video

before_script:
  - npm install -g grunt-cli
  - cd utils
  - npm install .

script:
  - grunt build
